services:
  - type: web
    name: babbelfish.ai
    env: python
    buildCommand: pip install -r requirements.txt && cd components && npm install --prefix elevenlabs_component/frontend && npm run build --prefix elevenlabs_component/frontend && npm install --prefix audio_component/frontend && npm run build --prefix audio_component/frontend 
    startCommand: streamlit run app.py
    pythonVersion: 3.10.14

